let songs = [
	"いつかの夢、またねの約束。 by TAKU1175 ft. 駄々子",
	"Prayer by ぺのれり",
	"INDEPENDENT SKY by SOUND HOLIC feat. Nana Takahashi",
	"VOLTEXES III by Sota Fujimori",
	"Lord=Crossight by ぺのれり",
	"ミュージックプレイヤー by Retropolitaliens(Ms.+駄々子)",
	'VALKYRIE ASSAULT by BEMANI Sound Team "SYUNN"',
	'Reb∞t by BEMANI Sound Team "TAG"',
	"MixxioN by MisoilePunch♪",
	"veRtrageS by Riz vs. Shiron",
	"Last Battalion by ETIA.",
	"SociuS by Ellim Gnirps vs よみぃ",
	"ボルテ体操第一 by Kaoru feat.FG75",
	"croiX by TeamGrimoire+あ ま猫",
	"Twin Blaster by polysha+tcheb",
	"Absolute Domination by Laur",
	"IKAROS DYNAMITE!!!! by BlackY",
	"Discloze by lapix",
	"Wings to fly high by Noah",
	"Hellfire by Hommarju",
	"FIN4LE ～終止線の彼方へ～ by カモメサノエレクトリックオーケストラ",
	"Яe:son D'être by SCHOOL CASTE(石見＆とおる)",
	"concon (picom'n'bass rmx) by kamome sano",
	"君は Fantasista by 杉下 トキヤ",
	"Dawn of Asia by ginkiha+kamome sano",
	"紅の剣舞 by かねこちは る",
	"666 by RoughSketch",
	"Poison Blood by udouddo",
	"Arcade Prison by MAD CHILD vs. siromaru",
	"CODE -CRiMSON- by Shiron",
	"ULTRAVELOCITY by はがね",
	"Wuv U(pico/ustic rmx) by kamome sano",
	"Staring at star by MisoilePunch♪ ～タケノコ添え～",
	"バタフライキャ ット by daniwell",
	"きらきらタイム☆ by さわわ",
	"マサカリブレイド by REDALiCE",
	"Growth Memories by Hidra-Xjeil",
	"REVOLVER by sky_delta",
	"Bangin' Burst by かめりあ",
	"FEEL THE FORCE by brz1128",
	"The star in eclipse by しーけー",
	"神話に芽吹く by Cororo",
	"Grand-Guignol by モリモリあつし",
	"Sourire by とろまる",
	"Appliqué by モリモリあつし",
	" 混乱少女♥そふらんちゃん!! by かめりあ feat. ななひら",
	"*Feels Seasickness...* by かめ りあ",
	"ゔぉるみっくす!!!! by かめりあ feat. ななひら",
	"JUNKIE FLAVOR by yaseta + Hidra-Xjeil",
	"ばらんが!!!! by かめりあ feat. ななひら",
	"VVelcome!! by MisoilePunch♪",
	"いでぃおで結構！ by 諸星なな feat.加藤はるか",
	"Chakra by uma",
	"Gorgetech by Shiron",
	"Sayonara Planet Wars by 黒魔",
	"GaLaXyEggPlanT by sasakure.UK",
	"大宇宙ステージ by 黒魔",
	"#SpeedyCats by RoughSketch a.k.a. uno(IOSYS)",
	"Pon-Pon-Pompoko Dai-Sen-Saw! by 黒魔",
	"KAC 2012 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- by FLOOR LEGENDS -KAC 2012-",
	"ド ゥサンコオデッセイ!! by cosMo＠暴走P",
	"十三不塔 by 隣の卓は役満(庭師+Aoi)",
	"Revvable Engine by nora2r",
	"METATRON by SHIKI",
	"GEROL by Hommarju",
	"抜刀 by 猫大樹",
	"愛昧シ ョコラーテ by 角巻わため",
	"Come to Life by ARM (IOSYS) feat. Nicole Curry",
	"断罪は遍 く人間の元に by Unlucky Morpheus",
	"snow storm -euphoria- by Yooh",
	"β by BlackY",
	"最 小三倍完全数 by DJ TECHNORCH",
	"WICKeD CRφSS by OSTER project",
	"ΕΛΠΙΣ by dj TAKA",
	"Turn the story by technoplanet feat. Kuroto Sion",
	"Sakura Mirage by Ryu☆",
	"ドゥンガドゥンガ狂詩曲 by かねこちはる + はぁち + 飛鳥男",
	"50th Memorial Songs -The BEMANI History- by BEMANI Sound Team",
	"VOLTEXES by Sota Fujimori",
	"Adrenaline Rush by siqlo",
	'MODEL FT4 by BEMANI Sound Team "Mutsuhiko Izumi"',
	"{albus} by かめりあ",
	"羅生門 by TAKU1175 × かにまゆ",
	"B.B.K.K.B.K.K. by nora2r",
	"Genesis At Oasis (Hirayasu Matsudo Remix) by Hirayasu Matsudo",
	"405nm(Shu※mix) by Shu※",
	"Mermaid girl (Tropical Remix) by Hyuji feat. LIQU@。",
	"VIVID DEBUT! by #EmoCosine",
	"empty by Λerdammt",
	"ぶいちゅっばの歌 by 周防パトラ",
	'QQ by BEMANI Sound Team "PHQUASE & ZAQUVA"',
	"無魎大数 by cosMo＠暴走P",
	"おお われら喜び讃うべし、主よ by すのうまん",
	"Gaze ft. 紫崎 雪 by Omnis",
	"Atropa bella-donna by HOUJIROU",
	'MOVE! (We Keep It Movin\') by Jonny Dynamite!,Lisa - paint with stars -,Rio Hiiragi by BEMANI Sound Team "U1-ASAMi"',
	"三つ数えろ by 豚乙女",
	"9TH5IN by ETIA.",
	"Bl∞min' by MisoilePunch♪ -Forever-",
	"Gimme dreamin' by BlackY feat. Risa Yuzuki",
	"Starlight Express by ginkiha",
	"Historia of Velnoti by KV.S&はらたま",
	"少年は空を辿る Prog Piano Remix by とろまる",
	"V by TAKA",
	"NEXT BILLIONAIRE by SOUND HOLIC feat. Nana Takahashi",
	"Gamerz FestivaL by うさぎ愛好会(cosMo×syuri22)",
	"Earthquake Super Shock - SDVX Edit. - by SOUND HOLIC feat. Nana Takahashi",
	"KIRAMEKI OVERDRIVE by FALL",
	"Hurt me plenty by Noah",
	"Harpuia by BlackY",
	"Wheel by Syrufit feat.綾倉盟 /  市松椿",
	"Love♡Shine わんだふるmix by ARM (IOSYS) feat. 一ノ瀬月琉 (monotone)",
	"Dooooope by RiMo",
	"PIERROT KNIfE by まろん (IOSYS)",
	"POSSESSION (Aoi Q.E.D. RMX) by Aoi",
	"十の試煉 by 打打だいず vs. siromaru",
	"CadenzaMaiden by u-z feat.紫咲ほたる",
	"GO BACK 2 YOUR RAVE by nora2r",
	"OUTERHEΛVEN by Juggernaut.",
	"ノイジーラバーソウル by Last Note. feat. GUMI",
	"∞vitUniverse by Lime",
	"恋獄対刃 by あるふぁ＋凜々",
	"ケロ⑨destiny by Silver Forest feat. めらみぽっぷ",
	"Finale by A-One",
	"八雲藍の唯心論 by 君の美術館",
	"分けるな危険！モモモモモモーイズム by ARM×狐夢想 feat. 桃井はるこ",
	"Call of the World by お月さま交響曲",
	"Oriental Blossom by 影翔鼓舞",
	"マツヨイナイトバグ by ビートまりおとまろん",
	"Don't you dare play GOD by technoplanet feat. Tamako Kinoshita",
]

let songs2 =
	`9TH5IN by ETIA. [CLEAR] (Pass) (MapleSDVX), 9TH5IN by ETIA. [CLEAR] (AA Rank) (MapleSDVX), 9TH5IN by ETIA. [CLEAR] (AAA Rank) (MapleSDVX), 9TH5IN by ETIA. [CLEAR] (S Rank) (MapleSDVX), OUTERHEΛVEN by Juggernaut. [CLEAR] (Pass) (MapleSDVX), OUTERHEΛVEN by Juggernaut. [CLEAR] (AA Rank) (MapleSDVX), OUTERHEΛVEN by Juggernaut. [CLEAR] (AAA Rank) (MapleSDVX), OUTERHEΛVEN by Juggernaut. [CLEAR] (S Rank) (MapleSDVX), QQ by BEMANI Sound Team "PHQUASE & ZAQUVA" [CLEAR] (Pass) (MapleSDVX), QQ by BEMANI Sound Team "PHQUASE & ZAQUVA" [CLEAR] (AA Rank) (MapleSDVX), QQ by BEMANI Sound Team "PHQUASE & ZAQUVA" [CLEAR] (AAA Rank) (MapleSDVX), QQ by BEMANI Sound Team "PHQUASE & ZAQUVA" [CLEAR] (S Rank) (MapleSDVX), snow storm -euphoria- by Yooh [CLEAR] (Pass) (MapleSDVX), snow storm -euphoria- by Yooh [CLEAR] (AA Rank) (MapleSDVX), snow storm -euphoria- by Yooh [CLEAR] (AAA Rank) (MapleSDVX), snow storm -euphoria- by Yooh [CLEAR] (S Rank) (MapleSDVX), ドゥサンコオデッセイ!! by cosMo＠暴走P [CLEAR] (Pass) (MapleSDVX), ドゥサンコオデッセイ!! by cosMo＠暴走P [CLEAR] (AA Rank) (MapleSDVX), ドゥサンコオデッセイ!! by cosMo＠暴走P [CLEAR] (AAA Rank) (MapleSDVX), ドゥサンコオデッセイ!! by cosMo＠暴走P [CLEAR] (S Rank) (MapleSDVX), 十の試煉 by 打打だいず vs. siromaru [CLEAR] (Pass) (MapleSDVX), 十の試煉 by 打打だいず vs. siromaru [CLEAR] (AA Rank) (MapleSDVX), 十の試煉 by 打打だいず vs. siromaru [CLEAR] (AAA Rank) (MapleSDVX), 十の試煉 by 打打だいず vs. siromaru [CLEAR] (S Rank) (MapleSDVX), Atropa bella-donna by HOUJIROU [CLEAR] (Pass) (MapleSDVX), Atropa bella-donna by HOUJIROU [CLEAR] (AA Rank) (MapleSDVX), Atropa bella-donna by HOUJIROU [CLEAR] (AAA Rank) (MapleSDVX), Atropa bella-donna by HOUJIROU [CLEAR] (S Rank) (MapleSDVX), B.B.K.K.B.K.K. by nora2r [CLEAR] (Pass) (MapleSDVX), B.B.K.K.B.K.K. by nora2r [CLEAR] (AA Rank) (MapleSDVX), B.B.K.K.B.K.K. by nora2r [CLEAR] (AAA Rank) (MapleSDVX), B.B.K.K.B.K.K. by nora2r [CLEAR] (S Rank) (MapleSDVX), CadenzaMaiden by u-z feat.紫咲ほたる [CLEAR] (Pass) (MapleSDVX), CadenzaMaiden by u-z feat.紫咲ほたる [CLEAR] (AA Rank) (MapleSDVX), CadenzaMaiden by u-z feat.紫咲ほたる [CLEAR] (AAA Rank) (MapleSDVX), CadenzaMaiden by u-z feat.紫咲ほ たる [CLEAR] (S Rank) (MapleSDVX), Call of the World by お月さま交響曲 [CLEAR] (Pass) (MapleSDVX), Call of the World by お月さま交響曲 [CLEAR] (AA Rank) (MapleSDVX), Call of the World by お月さま交響曲 [CLEAR] (AAA Rank) (MapleSDVX), Call of the World by お月さま交響曲 [CLEAR] (S Rank) (MapleSDVX), Come to Life by ARM (IOSYS) feat. Nicole Curry [CLEAR] (Pass) (MapleSDVX), Come to Life by ARM (IOSYS) feat. Nicole Curry [CLEAR] (AA Rank) (MapleSDVX), Come to Life by ARM (IOSYS) feat. Nicole Curry [CLEAR] (AAA Rank) (MapleSDVX), Come to Life by ARM (IOSYS) feat. Nicole Curry [CLEAR] (S Rank) (MapleSDVX), Gamerz FestivaL by うさぎ愛好会(cosMo×syuri22) [CLEAR] (Pass) (MapleSDVX), Gamerz FestivaL by うさぎ愛好会(cosMo×syuri22) [CLEAR] (AA Rank) (MapleSDVX), Gamerz FestivaL by うさぎ愛好会(cosMo×syuri22) [CLEAR] (AAA Rank) (MapleSDVX), Gamerz FestivaL by うさぎ愛好会(cosMo×syuri22) [CLEAR] (S Rank) (MapleSDVX), Harpuia by BlackY [CLEAR] (Pass) (MapleSDVX), Harpuia by BlackY [CLEAR] (AA Rank) (MapleSDVX), Harpuia by BlackY [CLEAR] (AAA Rank) (MapleSDVX), Harpuia by BlackY [CLEAR] (S Rank) (MapleSDVX), Hurt me plenty by Noah [CLEAR] (Pass) (MapleSDVX), Hurt me plenty by Noah [CLEAR] (AA Rank) (MapleSDVX), Hurt me plenty by Noah [CLEAR] (AAA Rank) (MapleSDVX), Hurt me plenty by Noah [CLEAR] (S Rank) (MapleSDVX), KAC 2012 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- by FLOOR LEGENDS -KAC 2012- [CLEAR] (Pass) (MapleSDVX), KAC 2012 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- by FLOOR LEGENDS -KAC 2012- [CLEAR] (AA Rank) (MapleSDVX), KAC 2012 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- by FLOOR LEGENDS -KAC 2012- [CLEAR] (AAA Rank) (MapleSDVX), KAC 2012 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- by FLOOR LEGENDS -KAC 2012- [CLEAR] (S Rank) (MapleSDVX), METATRON by SHIKI [CLEAR] (Pass) (MapleSDVX), METATRON by SHIKI [CLEAR] (AA Rank) (MapleSDVX), METATRON by SHIKI [CLEAR] (AAA Rank) (MapleSDVX), METATRON by SHIKI [CLEAR] (S Rank) (MapleSDVX), MODEL FT4 by BEMANI Sound Team "Mutsuhiko Izumi" [CLEAR] (Pass) (MapleSDVX), MODEL FT4 by BEMANI Sound Team "Mutsuhiko Izumi" [CLEAR] (AA Rank) (MapleSDVX), MODEL FT4 by BEMANI Sound Team "Mutsuhiko Izumi" [CLEAR] (AAA Rank) (MapleSDVX), MODEL FT4 by BEMANI Sound Team "Mutsuhiko Izumi" [CLEAR] (S Rank) (MapleSDVX), POSSESSION (Aoi Q.E.D. RMX) by Aoi [CLEAR] (Pass) (MapleSDVX), POSSESSION (Aoi Q.E.D. RMX) by Aoi [CLEAR] (AA Rank) (MapleSDVX), POSSESSION (Aoi Q.E.D. RMX) by Aoi [CLEAR] (AAA Rank) (MapleSDVX), POSSESSION (Aoi Q.E.D. RMX) by Aoi [CLEAR] (S Rank) (MapleSDVX), Revvable Engine by nora2r [CLEAR] (Pass) (MapleSDVX), Revvable Engine by nora2r [CLEAR] (AA Rank) (MapleSDVX), Revvable Engine by nora2r [CLEAR] (AAA Rank) (MapleSDVX), Revvable Engine by nora2r [CLEAR] (S Rank) (MapleSDVX), Turn the story by technoplanet feat. Kuroto Sion [CLEAR] (Pass) (MapleSDVX), Turn the story by technoplanet feat. Kuroto Sion [CLEAR] (AA Rank) (MapleSDVX), Turn the story by technoplanet feat. Kuroto Sion [CLEAR] (AAA Rank) (MapleSDVX), Turn the story by technoplanet feat. Kuroto Sion [CLEAR] (S Rank) (MapleSDVX), V by TAKA [CLEAR] (Pass) (MapleSDVX), V by TAKA [CLEAR] (AA Rank) (MapleSDVX), V by TAKA [CLEAR] (AAA Rank) (MapleSDVX), V by TAKA [CLEAR] (S Rank) (MapleSDVX), ∞vitUniverse by Lime [CLEAR] (Pass) (MapleSDVX), ∞vitUniverse by Lime [CLEAR] (AA Rank) (MapleSDVX), ∞vitUniverse by Lime [CLEAR] (AAA Rank) (MapleSDVX), ∞vitUniverse by Lime [CLEAR] (S Rank) (MapleSDVX), おお われら喜び讃うべし、主よ by すのうまん [CLEAR] (Pass) (MapleSDVX), おお われら喜び讃うべし、主よ by すのうまん [CLEAR] (AA Rank) (MapleSDVX), おお われら喜び讃うべし、主よ by すのうまん [CLEAR] (AAA Rank) (MapleSDVX), おお われら喜び讃うべし、主よ by すのうまん [CLEAR] (S Rank) (MapleSDVX), マツヨイナイトバグ by ビートまりおとまろん [CLEAR] (Pass) (MapleSDVX), マツヨイナイトバグ by ビートまりおとまろん [CLEAR] (AA Rank) (MapleSDVX), マツヨイナイトバグ by ビートまりおとまろ ん [CLEAR] (AAA Rank) (MapleSDVX), マツヨイナイトバグ by ビートまりおとまろん [CLEAR] (S Rank) (MapleSDVX), 十三不塔 by 隣の卓は役満(庭師+Aoi) [CLEAR] (Pass) (MapleSDVX), 十 三不塔 by 隣の卓は役満(庭師+Aoi) [CLEAR] (AA Rank) (MapleSDVX), 十三不塔 by 隣の卓は役 満(庭師+Aoi) [CLEAR] (AAA Rank) (MapleSDVX), 十三不塔 by 隣の卓は役満(庭師+Aoi) [CLEAR] (S Rank) (MapleSDVX), 最小三倍完全数 by DJ TECHNORCH [CLEAR] (Pass) (MapleSDVX), 最小 三倍完全数 by DJ TECHNORCH [CLEAR] (AA Rank) (MapleSDVX), 最小三倍完全数 by DJ TECHNORCH [CLEAR] (AAA Rank) (MapleSDVX), 最小三倍完全数 by DJ TECHNORCH [CLEAR] (S Rank) (MapleSDVX), 無魎大数 by cosMo＠暴走P [CLEAR] (Pass) (MapleSDVX), 無魎大数 by cosMo＠暴走P [CLEAR] (AA Rank) (MapleSDVX), 無魎大数 by cosMo＠暴走P [CLEAR] (AAA Rank) (MapleSDVX), 無魎大数 by cosMo＠暴走P [CLEAR] (S Rank) (MapleSDVX), 405nm(Shu※mix) by Shu※ [CLEAR] (Pass) (MapleSDVX), 405nm(Shu※mix) by Shu※ [CLEAR] (AA Rank) (MapleSDVX), 405nm(Shu※mix) by Shu※ [CLEAR] (AAA Rank) (MapleSDVX), 405nm(Shu※mix) by Shu※ [CLEAR] (S Rank) (MapleSDVX), 50th Memorial Songs -The BEMANI History- by BEMANI Sound Team [CLEAR] (Pass) (MapleSDVX), 50th Memorial Songs -The BEMANI History- by BEMANI Sound Team [CLEAR] (AA Rank) (MapleSDVX), 50th Memorial Songs -The BEMANI History- by BEMANI Sound Team [CLEAR] (AAA Rank) (MapleSDVX), 50th Memorial Songs -The BEMANI History- by BEMANI Sound Team [CLEAR] (S Rank) (MapleSDVX), Adrenaline Rush by siqlo [CLEAR] (Pass) (MapleSDVX), Adrenaline Rush by siqlo [CLEAR] (AA Rank) (MapleSDVX), Adrenaline Rush by siqlo [CLEAR] (AAA Rank) (MapleSDVX), Adrenaline Rush by siqlo [CLEAR] (S Rank) (MapleSDVX), Finale by A-One [CLEAR] (Pass) (MapleSDVX), Finale by A-One [CLEAR] (AA Rank) (MapleSDVX), Finale by A-One [CLEAR] (AAA Rank) (MapleSDVX), Finale by A-One [CLEAR] (S Rank) (MapleSDVX), Gimme dreamin' by BlackY feat. Risa Yuzuki [CLEAR] (Pass) (MapleSDVX), Gimme dreamin' by BlackY feat. Risa Yuzuki [CLEAR] (AA Rank) (MapleSDVX), Gimme dreamin' by BlackY feat. Risa Yuzuki [CLEAR] (AAA Rank) (MapleSDVX), Gimme dreamin' by BlackY feat. Risa Yuzuki [CLEAR] (S Rank) (MapleSDVX), Historia of Velnoti by KV.S&はらたま [CLEAR] (Pass) (MapleSDVX), Historia of Velnoti by KV.S&はらたま [CLEAR] (AA Rank) (MapleSDVX), Historia of Velnoti by KV.S&はらたま [CLEAR] (AAA Rank) (MapleSDVX), Historia of Velnoti by KV.S&はらたま [CLEAR] (S Rank) (MapleSDVX), MOVE! (We Keep It Movin') by Jonny Dynamite!,Lisa - paint with stars -,Rio Hiiragi by BEMANI Sound Team "U1-ASAMi" [CLEAR] (Pass) (MapleSDVX), MOVE! (We Keep It Movin') by Jonny Dynamite!,Lisa - paint with stars -,Rio Hiiragi by BEMANI Sound Team "U1-ASAMi" [CLEAR] (AA Rank) (MapleSDVX), MOVE! (We Keep It Movin') by Jonny Dynamite!,Lisa - paint with stars -,Rio Hiiragi by BEMANI Sound Team "U1-ASAMi" [CLEAR] (AAA Rank) (MapleSDVX), MOVE! (We Keep It Movin') by Jonny Dynamite!,Lisa - paint with stars -,Rio Hiiragi by BEMANI Sound Team "U1-ASAMi" [CLEAR] (S Rank) (MapleSDVX), PIERROT KNIfE by まろん (IOSYS) [CLEAR] (Pass) (MapleSDVX), PIERROT KNIfE by まろん (IOSYS) [CLEAR] (AA Rank) (MapleSDVX), PIERROT KNIfE by まろん (IOSYS) [CLEAR] (AAA Rank) (MapleSDVX), PIERROT KNIfE by まろん (IOSYS) [CLEAR] (S Rank) (MapleSDVX), Sakura Mirage by Ryu☆ [CLEAR] (Pass) (MapleSDVX), Sakura Mirage by Ryu☆ [CLEAR] (AA Rank) (MapleSDVX), Sakura Mirage by Ryu☆ [CLEAR] (AAA Rank) (MapleSDVX), Sakura Mirage by Ryu☆ [CLEAR] (S Rank) (MapleSDVX), VIVID DEBUT! by #EmoCosine [CLEAR] (Pass) (MapleSDVX), VIVID DEBUT! by #EmoCosine [CLEAR] (AA Rank) (MapleSDVX), VIVID DEBUT! by #EmoCosine [CLEAR] (AAA Rank) (MapleSDVX), VIVID DEBUT! by #EmoCosine [CLEAR] (S Rank) (MapleSDVX), WICKeD CRφSS by OSTER project [CLEAR] (Pass) (MapleSDVX), WICKeD CRφSS by OSTER project [CLEAR] (AA Rank) (MapleSDVX), WICKeD CRφSS by OSTER project [CLEAR] (AAA Rank) (MapleSDVX), WICKeD CRφSS by OSTER project [CLEAR] (S Rank) (MapleSDVX), Wheel by Syrufit feat.綾倉盟 / 市松椿 [CLEAR] (Pass) (MapleSDVX), Wheel by Syrufit feat.綾倉盟 / 市松椿 [CLEAR] (AA Rank) (MapleSDVX), Wheel by Syrufit feat.綾倉盟 / 市松椿 [CLEAR] (AAA Rank) (MapleSDVX), Wheel by Syrufit feat.綾倉盟 / 市松椿 [CLEAR] (S Rank) (MapleSDVX), empty by Λerdammt [CLEAR] (Pass) (MapleSDVX), empty by Λerdammt [CLEAR] (AA Rank) (MapleSDVX), empty by Λerdammt [CLEAR] (AAA Rank) (MapleSDVX), empty by Λerdammt [CLEAR] (S Rank) (MapleSDVX), {albus} by かめりあ [CLEAR] (Pass) (MapleSDVX), {albus} by かめりあ [CLEAR] (AA Rank) (MapleSDVX), {albus} by かめりあ [CLEAR] (AAA Rank) (MapleSDVX), {albus} by かめりあ [CLEAR] (S Rank) (MapleSDVX), ΕΛΠΙΣ by dj TAKA [CLEAR] (Pass) (MapleSDVX), ΕΛΠΙΣ by dj TAKA [CLEAR] (AA Rank) (MapleSDVX), ΕΛΠΙΣ by dj TAKA [CLEAR] (AAA Rank) (MapleSDVX), ΕΛΠΙΣ by dj TAKA [CLEAR] (S Rank) (MapleSDVX), β by BlackY [CLEAR] (Pass) (MapleSDVX), β by BlackY [CLEAR] (AA Rank) (MapleSDVX), β by BlackY [CLEAR] (AAA Rank) (MapleSDVX), β by BlackY [CLEAR] (S Rank) (MapleSDVX), ぶいちゅっばの歌 by 周防パトラ [CLEAR] (Pass) (MapleSDVX), ぶいちゅっばの歌 by 周防パトラ [CLEAR] (AA Rank) (MapleSDVX), ぶ いちゅっばの歌 by 周防パトラ [CLEAR] (AAA Rank) (MapleSDVX), ぶいちゅっばの歌 by 周防パトラ [CLEAR] (S Rank) (MapleSDVX), ケロ⑨destiny by Silver Forest feat. めらみぽっぷ [CLEAR] (Pass) (MapleSDVX), ケロ⑨destiny by Silver Forest feat. めらみぽっぷ [CLEAR] (AA Rank) (MapleSDVX), ケロ⑨destiny by Silver Forest feat. めらみぽっぷ [CLEAR] (AAA Rank) (MapleSDVX), ケロ⑨destiny by Silver Forest feat. めらみぽっぷ [CLEAR] (S Rank) (MapleSDVX), 分けるな危険！モモモモモモーイズム by ARM×狐夢想 feat. 桃井はるこ [CLEAR] (Pass) (MapleSDVX), 分けるな危険！モモモモモモーイズム by ARM×狐夢想 feat. 桃井はるこ [CLEAR] (AA Rank) (MapleSDVX), 分けるな危険！モモモモモモーイズム by ARM×狐夢想 feat. 桃井はるこ [CLEAR] (AAA Rank) (MapleSDVX), 分けるな危険！モモモモモモーイズム by ARM×狐夢想 feat. 桃井はるこ [CLEAR] (S Rank) (MapleSDVX), 少年は空を辿る Prog Piano Remix by とろまる [CLEAR] (Pass) (MapleSDVX), 少年は空を辿る Prog Piano Remix by とろまる [CLEAR] (AA Rank) (MapleSDVX), 少年は空を辿る Prog Piano Remix by とろまる [CLEAR] (AAA Rank) (MapleSDVX), 少年は空を辿る Prog Piano Remix by とろまる [CLEAR] (S Rank) (MapleSDVX), 恋獄対刃 by あるふぁ＋凜々 [CLEAR] (Pass) (MapleSDVX), 恋獄対刃 by あるふぁ＋凜々 [CLEAR] (AA Rank) (MapleSDVX), 恋獄対刃 by あるふぁ＋凜々 [CLEAR] (AAA Rank) (MapleSDVX), 恋獄対刃 by あるふぁ＋凜々 [CLEAR] (S Rank) (MapleSDVX), 断罪は遍く人間の元に by Unlucky Morpheus [CLEAR] (Pass) (MapleSDVX), 断罪は遍く人間の元に by Unlucky Morpheus [CLEAR] (AA Rank) (MapleSDVX), 断罪は遍く人間の元に by Unlucky Morpheus [CLEAR] (AAA Rank) (MapleSDVX), 断罪は遍く人間の元に by Unlucky Morpheus [CLEAR] (S Rank) (MapleSDVX), 羅生門 by TAKU1175 × かにまゆ [CLEAR] (Pass) (MapleSDVX), 羅生門 by TAKU1175 × かにまゆ [CLEAR] (AA Rank) (MapleSDVX), 羅生門 by TAKU1175 × かにまゆ [CLEAR] (AAA Rank) (MapleSDVX), 羅生門 by TAKU1175 × かにまゆ [CLEAR] (S Rank) (MapleSDVX), Dooooope by RiMo [CLEAR] (Pass) (MapleSDVX), Dooooope by RiMo [CLEAR] (AA Rank) (MapleSDVX), Dooooope by RiMo [CLEAR] (AAA Rank) (MapleSDVX), Dooooope by RiMo [CLEAR] (S Rank) (MapleSDVX), GEROL by Hommarju [CLEAR] (Pass) (MapleSDVX), GEROL by Hommarju [CLEAR] (AA Rank) (MapleSDVX), GEROL by Hommarju [CLEAR] (AAA Rank) (MapleSDVX), GEROL by Hommarju [CLEAR] (S Rank) (MapleSDVX), GO BACK 2 YOUR RAVE by nora2r [CLEAR] (Pass) (MapleSDVX), GO BACK 2 YOUR RAVE by nora2r [CLEAR] (AA Rank) (MapleSDVX), GO BACK 2 YOUR RAVE by nora2r [CLEAR] (AAA Rank) (MapleSDVX), GO BACK 2 YOUR RAVE by nora2r [CLEAR] (S Rank) (MapleSDVX), Genesis At Oasis (Hirayasu Matsudo Remix) by Hirayasu Matsudo [CLEAR] (Pass) (MapleSDVX), Genesis At Oasis (Hirayasu Matsudo Remix) by Hirayasu Matsudo [CLEAR] (AA Rank) (MapleSDVX), Genesis At Oasis (Hirayasu Matsudo Remix) by Hirayasu Matsudo [CLEAR] (AAA Rank) (MapleSDVX), Genesis At Oasis (Hirayasu Matsudo Remix) by Hirayasu Matsudo [CLEAR] (S Rank) (MapleSDVX), KIRAMEKI OVERDRIVE by FALL [CLEAR] (Pass) (MapleSDVX), KIRAMEKI OVERDRIVE by FALL [CLEAR] (AA Rank) (MapleSDVX), KIRAMEKI OVERDRIVE by FALL [CLEAR] (AAA Rank) (MapleSDVX), KIRAMEKI OVERDRIVE by FALL [CLEAR] (S Rank) (MapleSDVX), Oriental Blossom by 影翔鼓舞 [CLEAR] (Pass) (MapleSDVX), Oriental Blossom by 影翔鼓舞 [CLEAR] (AA Rank) (MapleSDVX), Oriental Blossom by 影翔鼓舞 [CLEAR] (AAA Rank) (MapleSDVX), Oriental Blossom by 影翔鼓舞 [CLEAR] (S Rank) (MapleSDVX), Starlight Express by ginkiha [CLEAR] (Pass) (MapleSDVX), Starlight Express by ginkiha [CLEAR] (AA Rank) (MapleSDVX), Starlight Express by ginkiha [CLEAR] (AAA Rank) (MapleSDVX), Starlight Express by ginkiha [CLEAR] (S Rank) (MapleSDVX), ドゥンガドゥンガ狂詩曲 by かねこちはる + はぁち + 飛鳥男 [CLEAR] (Pass) (MapleSDVX), ドゥンガドゥンガ狂詩曲 by かねこちはる + はぁち + 飛鳥男 [CLEAR] (AA Rank) (MapleSDVX), ドゥンガドゥンガ狂詩曲 by かねこちはる + はぁち + 飛鳥男 [CLEAR] (AAA Rank) (MapleSDVX), ドゥンガドゥンガ狂詩曲 by かねこちはる + はぁち + 飛鳥男 [CLEAR] (S Rank) (MapleSDVX), 三つ数えろ by 豚乙女 [CLEAR] (Pass) (MapleSDVX), 三つ数えろ by 豚乙女 [CLEAR] (AA Rank) (MapleSDVX), 三つ数えろ by 豚乙女 [CLEAR] (AAA Rank) (MapleSDVX), 三つ数えろ by  豚乙女 [CLEAR] (S Rank) (MapleSDVX), 愛昧ショコラーテ by 角巻わため [CLEAR] (Pass) (MapleSDVX), 愛昧ショコラーテ by 角巻わため [CLEAR] (AA Rank) (MapleSDVX), 愛昧ショコラーテ by 角巻わため [CLEAR] (AAA Rank) (MapleSDVX), 愛昧ショコラーテ by 角巻わため [CLEAR] (S Rank) (MapleSDVX), 抜刀 by 猫大樹 [CLEAR] (Pass) (MapleSDVX), 抜刀 by 猫大樹 [CLEAR] (AA Rank) (MapleSDVX), 抜刀 by 猫大樹 [CLEAR] (AAA Rank) (MapleSDVX), 抜刀 by 猫大樹 [CLEAR] (S Rank) (MapleSDVX), Earthquake Super Shock - SDVX Edit. - by SOUND HOLIC feat. Nana Takahashi [CLEAR] (Pass) (MapleSDVX), Earthquake Super Shock - SDVX Edit. - by SOUND HOLIC feat. Nana Takahashi [CLEAR] (AA Rank) (MapleSDVX), Earthquake Super Shock - SDVX Edit. - by SOUND HOLIC feat. Nana Takahashi [CLEAR] (AAA Rank) (MapleSDVX), Earthquake Super Shock - SDVX Edit. - by SOUND HOLIC feat. Nana Takahashi [CLEAR] (S Rank) (MapleSDVX), Gaze ft. 紫崎 雪 by Omnis [CLEAR] (Pass) (MapleSDVX), Gaze ft. 紫崎 雪 by Omnis [CLEAR] (AA Rank) (MapleSDVX), Gaze ft. 紫崎 雪 by Omnis [CLEAR] (AAA Rank) (MapleSDVX), Gaze ft. 紫崎 雪 by Omnis [CLEAR] (S Rank) (MapleSDVX), Mermaid girl (Tropical Remix) by Hyuji feat. LIQU@。 [CLEAR] (Pass) (MapleSDVX), Mermaid girl (Tropical Remix) by Hyuji feat. LIQU@。 [CLEAR] (AA Rank) (MapleSDVX), Mermaid girl (Tropical Remix) by Hyuji feat. LIQU@。 [CLEAR] (AAA Rank) (MapleSDVX), Mermaid girl (Tropical Remix) by Hyuji feat. LIQU@。 [CLEAR] (S Rank) (MapleSDVX), NEXT BILLIONAIRE by SOUND HOLIC feat. Nana Takahashi [CLEAR] (Pass) (MapleSDVX), NEXT BILLIONAIRE by SOUND HOLIC feat. Nana Takahashi [CLEAR] (AA Rank) (MapleSDVX), NEXT BILLIONAIRE by SOUND HOLIC feat. Nana Takahashi [CLEAR] (AAA Rank) (MapleSDVX), NEXT BILLIONAIRE by SOUND HOLIC feat. Nana Takahashi [CLEAR] (S Rank) (MapleSDVX), VOLTEXES by Sota Fujimori [CLEAR] (Pass) (MapleSDVX), VOLTEXES by Sota Fujimori [CLEAR] (AA Rank) (MapleSDVX), VOLTEXES by Sota Fujimori [CLEAR] (AAA Rank) (MapleSDVX), VOLTEXES by Sota Fujimori [CLEAR] (S Rank) (MapleSDVX), ノイ ジーラバーソウル by Last Note. feat. GUMI [CLEAR] (Pass) (MapleSDVX), ノイジーラバーソ ウル by Last Note. feat. GUMI [CLEAR] (AA Rank) (MapleSDVX), ノイジーラバーソウル by Last Note. feat. GUMI [CLEAR] (AAA Rank) (MapleSDVX), ノイジーラバーソウル by Last Note. feat. GUMI [CLEAR] (S Rank) (MapleSDVX), 八雲藍の唯心論 by 君の美術館 [CLEAR] (Pass) (MapleSDVX), 八雲藍の唯心論 by 君の美術館 [CLEAR] (AA Rank) (MapleSDVX), 八雲藍の唯心論 by 君の美術館 [CLEAR] (AAA Rank) (MapleSDVX), 八雲藍の唯心論 by 君の美術館 [CLEAR] (S Rank) (MapleSDVX), Love♡Shine わんだふるmix by ARM (IOSYS) feat. 一ノ瀬月琉 (monotone) [CLEAR] (Pass) (MapleSDVX), Love♡Shine わんだふるmix by ARM (IOSYS) feat. 一ノ瀬月琉 (monotone) [CLEAR] (AA Rank) (MapleSDVX), Love♡Shine わんだふるmix by ARM (IOSYS) feat. 一 ノ瀬月琉 (monotone) [CLEAR] (AAA Rank) (MapleSDVX), Love♡Shine わんだふるmix by ARM (IOSYS) feat. 一ノ瀬月琉 (monotone) [CLEAR] (S Rank) (MapleSDVX)`.split(
		", ",
	)

console.log(new Set(songs).intersection(new Set(songs2)))
